### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [19]:
import numpy as np
def analisis_array1d(array):
    if (array.ndim !=1):
        print("Dimensión de array errónea")
    else:
        print("Valor medio : "+str(round(np.mean(array),2)))
        print("Valor mediana: "+str(round(np.median(array),2)))
        print("valor varianza: "+str(round(np.var(array),2)))
        print("Valor desviación standard: "+str(round(np.std(array),2)))
        print("Valor primer cuantil: "+str(round(np.percentile(array,25),2)))
        print("Valor tercer cuantil: "+str(round(np.percentile(array,75),2)))
        
array_ejemplo=np.array([2,3,2,4,1,2,3,4,5,7,9,43,2,34,9])
print(array_ejemplo)
analisis_array1d(array_ejemplo)
print()

array_ej2=np.array([[2,3],[2,34]])
print(array_ej2)
analisis_array1d(array_ej2)
print()
array_ej3=np.array([1,1,1,1,1,1])
print(array_ej3)
analisis_array1d(array_ej3)

[ 2  3  2  4  1  2  3  4  5  7  9 43  2 34  9]
Valor medio : 8.67
Valor mediana: 4.0
valor varianza: 145.42
Valor desviación standard: 12.06
Valor primer cuantil: 2.0
Valor tercer cuantil: 8.0

[[ 2  3]
 [ 2 34]]
Dimensión de array errónea

[1 1 1 1 1 1]
Valor medio : 1.0
Valor mediana: 1.0
valor varianza: 0.0
Valor desviación standard: 0.0
Valor primer cuantil: 1.0
Valor tercer cuantil: 1.0


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


In [20]:

#generar numero y despues reshape

import random

def generador_aleat(veces):
     return random.sample(range(0,100),veces*veces)

dimension=input("Introduce el valor de la forma de la matriz NxN")
dimension=int(dimension) #pasamos a int , sin control de errores 
matriz=np.array(generador_aleat(dimension))

mat_final=matriz.reshape(dimension,dimension)
print(mat_final)

[[15 25  1 23]
 [52 88 78 20]
 [93 59 82 50]
 [62 99 43 35]]


### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [21]:
import numpy as np
import random

medida1=random.randint(2,10)
medida2=random.randint(2,10)
matriz=np.array(random.sample(range(0,100),medida1*medida2))
matriz=matriz.reshape(medida1,medida2)
#column,row=3,5
#a=np.array([range(row)for _ in range(column)])#añadir random y #medidas dim
print("La matriz ejemplo: ")
print(matriz)

maximos_filas=[]
def suma_filas(array):
    #suma por filas:
    for x in array:
        acumulacion=0
        for i in x:
            acumulacion+=i
        maximos_filas.append(acumulacion)
    print(maximos_filas)
print("La suma de las filas calculado mediante bucle:")    
suma_filas(matriz)


La matriz ejemplo: 
[[75 19 88 26 82]
 [34  4 91 21 96]
 [30 23 41 86 55]
 [68 60 20 51 66]
 [77 33  5 56 38]
 [94 12 97 16 59]]
La suma de las filas calculado mediante bucle:
[290, 246, 235, 265, 209, 278]


In [22]:
#modo DAtaScience
print("Calculadas con fuunciones de numpy")
print("Totales de cada columna "+str(np.add.reduce(matriz,axis=0)))#suma columnas
print("Totales de cada fila "+str(np.add.reduce(matriz,axis=1)))#suma filas



Calculadas con fuunciones de numpy
Totales de cada columna [378 151 342 256 396]
Totales de cada fila [290 246 235 265 209 278]


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [23]:
import numpy as np
np.random.seed (100)

#crea una matriz de 50 enteros aleatorios entre 0 y 10
var1 = np.random.randint (0, 10, 50)
print("Variable1: "+ str(var1))
#crear una matriz correlacionada positivamente con algo de ruido aleatorio
var2 = var1 + np.random.normal (0, 10, 50)
print("variable2: "+str(var2))

#calcular la correlación entre las dos matrices
print("Coeficiente correlación "+str(np.corrcoef(var1, var2)[0,1]))
 
print()
print("Coeficiente calculado mediante función corrcoef de numpy")

Variable1: [8 8 3 7 7 0 4 2 5 2 2 2 1 0 8 4 0 9 6 2 4 1 5 3 4 4 3 7 1 1 7 7 0 2 9 9 3
 2 5 8 1 0 7 6 2 0 8 2 5 1]
variable2: [ 13.92575746   8.37958129   6.71967572  10.59753947   5.59603535
  -4.43738512   9.68770162   7.38488768  18.15574179  16.78978297
   4.21426255  -9.17894159  -0.8499993   -4.31187446   9.42536252
 -10.96393454   3.0687456    8.5365277   10.17144275  -4.03770522
  10.85967248   9.59973786   6.91555442  14.78227928  10.00283569
 -14.44659863   3.4258809    6.75915012   4.84057844   0.50907502
  -9.01691177   5.61237434   0.12086266 -10.98144167   7.71113962
   6.17078367   1.20831746   8.75751769  28.80595342  -3.46700861
  -1.91143345  -8.54225772  15.63406468   2.8361877   -7.02225772
  -7.38562393   4.04661119   2.84200853   3.14377547  12.08439231]
Coeficiente correlación 0.3350183976385703

Coeficiente calculado mediante función corrcoef de numpy



- El coeficiente de correlación nos da una idea númerica de lo cercana que es la relación lineal entre 2 variables.Para su calculo nos podemos aproximar desde la idea de que el coeficiente de correlación es el valor de covarianza estandarizado por las desviaciones estandard de las variables individuales .<I>(ρ=Cov(X,Y)/σxσy)</I>



In [24]:
import numpy as np
def calculo_corr(var1,var2):
    numerador=np.multiply((var1-np.mean(var1)),(var2-np.mean(var2)))
    denominador=np.std(var2)*np.std(var1)
    print(np.mean(numerador/denominador))
    
calculo_corr(var1,var2)
print("Calculado mediante la covarianza y las desviaciones estandard")

0.3350183976385703
Calculado mediante la covarianza y las desviaciones estandard


- Lo ideal es graficar los puntos para comrpobar si hay puntos anormales que hagan que el valor de correlación nos haga asumir hipótesis erróneas.
- Por otro lado que el valor de la correlación sea alto (es decir cercano a 1), no tiene porque ser una prueba de casualidad entre las 2 variables.
- Por supuesto , el coeficiente de correlación lineal solo sirve para procesos que se ajustan a relaciones lineales. Si las variables se relacionan por otro tipo de relación no nos servirá.